### ISSUE TITLE
Website not working correctly

### ISSUE THREAD

**Issue by Arturr-H** [AaronKanaron/kanaron#2]
Hello dear friend. I'm using a ubuntu 5x^92 5" laptop with operaGX version 1.5.42.9 driver 5xOm-Processor and your website is rendering kinda funny. please fix it immediatly.

**Comment by AaronKanaron** [comment]
Fuck you

**Comment by Arturr-H** [comment]
> Fuck you

That's very unpleasant of you to say. If was considering donating some money for your cancer problems however now I'm just gonna ignore you.

**Comment by AaronKanaron** [comment]
No!!!! PLEASE My ganser is evolving to fighter-type lever 15. It it hard!

**Comment by Arturr-H** [comment]
Suck my what???? My at least I don't do not doing having a cancer ♋️💪🙄

**Comment by Arturr-H** [comment]
Hey 👋 what is a plan on doing today at my dad for dinner 🍽. I say you, walking down the street. You were so fine. I just had to beat. You loooked me in the eyes, I saw you eyes 👀 🥴🥴🥴

**Comment by Arturr-H** [comment]
🤙🙂 ~ hallå? Någon där i telefonen? 📞 ~ ja en naken gammal man. 🤙🤨 ~ ojoj knaskalas, min telefon fungerar inte kan vi ringa på FaceTime?

**Comment by AaronKanaron** [comment]
This is actually very inappropriate! My mother assed away when she her mom died when sher mom birthed and therefore she did doesnt get a bitherdeay. Now you are assulting my

**Comment by Arturr-H** [comment]
Yo mama so FAT, a man walking past thought she was MOUNT EVEREST

**Comment by AaronKanaron** [comment]
Yo mama är så fet att aktiemarknaden sjunker när hon hoppar över en måltid.

**Comment by AaronKanaron** [comment]
Yo Mama ist so fett, wenn sie sich einen Pelzmantel kauft, wird eine ganze Tierart aussterben.

**Comment by Arturr-H** [comment]
Yo mama so fat, she's diabetes am don't-n't having

**Comment by AaronKanaron** [comment]
I have stage 2 caner -- NOT!!!!!!!!!!!!!!!!!!!!!!!!!'
Borat (eigentlich Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan) ist eine amerikanische Filmkomödie aus dem Jahr 2006, die auf der Figur Borat Sagdiyev des britischen Komikers Sacha Baron Cohen basiert. Der Film ist eine satirische, fiktive Dokumentation. Im Jahr 2020 wurde die Fortsetzung Borat Subsequent Moviefilm veröffentlicht.
