### ISSUE TITLE
👋 what’s up. Today I encountered yet another issue.

### ISSUE THREAD

**Issue by Arturr-H** [AaronKanaron/kanaron#4]
I was planning on opening your code base using my abarantugo Ubuntu-gx version 18.92.5 clone, inside of the terminal of my own kernel using nvram to process visual tasks. Your code does not even respond. Please fix.

**Comment by AaronKanaron** [comment]
Sorry! Unfortunately that is a bug of abarantugo. Please choose another better OS like macintosh or windows. Thanks!

**Comment by Arturr-H** [comment]
Yes this is disrespectful. #allComputersAreGood man y you gotta bully people like this. Not okay 👍 I just got the message I got you 😉
